# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true
reviews:
  path_filters:
  - "!vendor/**"
  path_instructions:
    - path: '**'
      instructions: >-
        Focus on major issues impacting performance, readability,
        maintainability and security. Do not flag nitpicks. Do not
        suggest changes to pre-existing code that is not part of the diff.
  auto_apply_labels: true
  labeling_instructions:
    - label: "coderabbit-satisfied"
      instructions: >-
        Apply this label only if all review comments have been resolved
        and you are satisfied with the PR. Remove it if new issues are
        found, unresolved comments remain, or new commits are pushed.
  pre_merge_checks:
    docstrings:
      mode: off
